[package]
name = "tag2"
description = "TBA"
license = "ISC"
readme = "README.md"
repository = "https://github.com/ctsrc/repotools/tree/master/tag2"
version = "0.0.0"
authors = ["Erik Nordstr√∏m <erik@nordstroem.no>"]
edition = "2018"

[[bin]]
name = "tag"
path = "src/main.rs"

[dependencies]
